### ISSUE TITLE
community-nozzles link is not available

### ISSUE THREAD

**Issue by dburkhalter-pivotal** [pivotal-cf/docs-metrics-forwarder#3]
https://github.com/cloudfoundry/loggregator/blob/develop/docs/community-nozzles.md

**Comment by seviet** [comment]
thanks for reporting this @dburkhalter-pivotal! it looks like the updated link should be: https://github.com/cloudfoundry/loggregator-release/blob/develop/docs/community-nozzles.md

we'll update the docs.
